#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#  username, user id, and user home directory path only should be displayed.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
