#!/usr/bin/env bash
# This script will display number from 1-20 using case statement
t=1
while [ $t -lt 21 ];
do
	echo "$t"
	case $t in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((t++))
done
